security.jwt.secret=3fJ7#xD9pQ4&sL0vV8^tM2wZ1kB6N5gR
security.jwt.expiration=86400000

server.forward-headers-strategy=native

# ---------------------------------------------------
# ????
# ---------------------------------------------------
spring.application.name=user_info

# ---------------------------------------------------
# ??????user_info ????/???????
# ---------------------------------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/user_info?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=app_user
spring.datasource.password=app_pwd_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ---------------------------------------------------
# ??????chat ??????????
# ---------------------------------------------------
# ?? chat.datasource ??? ChatDataSourceConfig.java ? @ConfigurationProperties ????
chat.datasource.url=jdbc:mysql://localhost:3306/chat?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
chat.datasource.username=chat_user
chat.datasource.password=chat_pwd_456
chat.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ?? chat ???? JPA ??????????
chat.jpa.hibernate.ddl-auto=update
chat.jpa.show-sql=true
chat.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


